name: Test Frontend
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t marc89763/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true marc89763/react-test npm test
